version: '3.1'
services:
  app:
    container_name: app-universal
    build: .
    volumes:
      - ./app:/usr/web
      - /usr/web/node_modules/
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "7070:7070"
    environment:
      PORT: ${CLIENT_PORT}
      SERVER: ${SERVER_PORT}
      VIRTUAL_HOST: webapp.docker
      VIRTUAL_PORT: 7070
      REACT_APP_URL: ${REACT_APP_URL}:${CLIENT_PORT}
      REACT_APP_STYLES_URL: ${REACT_APP_STYLES_URL}
      NODE_ENV: ${NODE_ENV}
      BABEL_ENV: ${BABEL_ENV}
    restart: always
